#!/usr/bin/env python3
"""Generate commands/plumbing/config_sync.gohtml from deploy/panel.json.

Usage: scripts/gen-config-sync.py [--check] [--panel PATH] [--out PATH]
       (or `make config-sync`, which writes the file)

config_sync is an hourly interval command that merges every managed command's panel id
into the `Commands` DB dict, one id map per server in panel.json "servers", chosen by
`.Guild.ID`. Keys are the command file's basename without `.gohtml`; values are the id as
a string (as bootstrap stored them; every reader does `toInt`). Entries under retired/ are
skipped, as deploy-manifest.py skips them, and so is a server a command has no id for.

--check writes nothing: it exits 1 (with a hint to run `make config-sync`) when the file
at --out differs from what this script would write, and 0 when it matches.

Exits 2 (message on stderr) when two panel.json entries share a basename: they would
write the same Commands key.
"""
import argparse
import json
import os
import sys

PANEL_JSON = "deploy/panel.json"
OUT = "commands/plumbing/config_sync.gohtml"

HEADER = """{{- /*
  Author: Vladlena Costescu (@lbds137)
  Trigger type: `Hourly interval`
  Interval: `1`
  Group: `Staff Utility`
  Dependencies: none

  Generated by scripts/gen-config-sync.py from deploy/panel.json: edit panel.json and
  run `make config-sync`, never edit this file by hand.

  Merges every managed command's panel id into the Commands dict (keys it doesn't know
  stay), as a string, for this server only (a server not in panel.json is left alone).
  One dbGet and one dbSet per run, no output (an interval run's output would post).
*/ -}}
"""


class GenerateError(Exception):
    pass


def id_maps(panel):
    """Return [(server, guild, {key: id string})] in panel.json's server order."""
    keys_by_basename = {}
    for path in panel["commands"]:
        if path.startswith("retired/"):
            continue
        key = os.path.basename(path)
        if key.endswith(".gohtml"):
            key = key[: -len(".gohtml")]
        if key in keys_by_basename:
            raise GenerateError(
                f"duplicate basename {key!r}: {keys_by_basename[key]} and {path} "
                "would write the same Commands key"
            )
        keys_by_basename[key] = path

    maps = []
    for server, info in panel["servers"].items():
        ids = {}
        for key, path in keys_by_basename.items():
            server_ids = panel["commands"][path]
            if server in server_ids:
                ids[key] = str(server_ids[server])
        maps.append((server, str(info["guild"]), dict(sorted(ids.items()))))
    return maps


def generate(panel):
    lines = [HEADER.rstrip("\n"), "", "{{- $ids := sdict -}}"]
    first = True
    for server, guild, ids in id_maps(panel):
        if not guild.isdigit():
            raise GenerateError(f"server {server}: guild {guild!r} is not a number")
        if not ids:
            continue
        keyword = "if" if first else "else if"
        first = False
        lines.append(f"{{{{- {keyword} eq .Guild.ID {guild} -}}}}")
        lines.append(f"    {{{{- /* {server} */ -}}}}")
        lines.append("    {{- $ids = sdict")
        for key, value in ids.items():
            lines.append(f"        {json.dumps(key)} {json.dumps(value)}")
        # a `-}}` alone on its own line doesn't parse in YAGPDB: close on the last pair
        lines[-1] += " -}}"
    if not first:
        lines.append("{{- end -}}")
    lines += [
        "",
        "{{- if $ids -}}",
        '    {{- $commandsDict := or (dbGet 0 "Commands").Value sdict -}}',
        "    {{- range $key, $id := $ids -}}",
        "        {{- $commandsDict.Set $key $id -}}",
        "    {{- end -}}",
        '    {{- dbSet 0 "Commands" $commandsDict -}}',
        "{{- end -}}",
    ]
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the output file is stale, write nothing")
    parser.add_argument("--panel", default=PANEL_JSON, help="panel.json to read")
    parser.add_argument("--out", default=OUT, help="file to write or check")
    args = parser.parse_args(argv)

    with open(args.panel, encoding="utf-8") as f:
        panel = json.load(f)
    try:
        content = generate(panel)
    except GenerateError as e:
        print(f"gen-config-sync: {e}", file=sys.stderr)
        return 2

    if args.check:
        try:
            with open(args.out, encoding="utf-8", newline="") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != content:
            print(f"{args.out} is stale or missing (run: make config-sync)", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date with {args.panel}")
        return 0

    with open(args.out, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
