#!/bin/bash
# Regenerate the list of YAGPDB template function names used by the emulator's error hints.
# Reads vendor/yagpdb (fetch it with vendor/update-yagpdb.sh first).
# Usage: ./scripts/gen-yagpdb-funcs.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
YAGPDB="$PROJECT_ROOT/vendor/yagpdb"
OUT="$PROJECT_ROOT/tools/emulator/internal/runtime/yagpdb_funcs.go"

if [[ ! -d "$YAGPDB/common/templates" ]]; then
    echo "vendor/yagpdb is missing; run vendor/update-yagpdb.sh first" >&2
    exit 1
fi

REV="$(git -C "$YAGPDB" rev-parse --short HEAD)"

NAMES="$(
    {
        # Standard functions: the StandardFuncMap literal
        awk '/StandardFuncMap = map/{p=1; next} p && /^\t}/{exit} p' "$YAGPDB/common/templates/context.go" \
            | grep -oE '^\s*"[A-Za-z0-9]+":'
        # Context functions registered by the template package and by plugins
        grep -rhoE 'addContextFunc\("[A-Za-z0-9]+"' --include=*.go "$YAGPDB"
        grep -rhoE 'ContextFuncs\["[A-Za-z0-9]+"\]' --include=*.go "$YAGPDB"
    } | grep -oE '"[A-Za-z0-9]+"' | tr -d '"' | sort -u
)"

{
    echo "// Code generated by scripts/gen-yagpdb-funcs.sh from YAGPDB $REV. DO NOT EDIT."
    echo
    echo "package runtime"
    echo
    echo "// yagpdbFuncs lists the template functions YAGPDB defines, so an error about an"
    echo "// unknown function can tell a typo apart from a function the emulator lacks."
    echo "var yagpdbFuncs = map[string]bool{"
    while read -r name; do
        printf '\t"%s": true,\n' "$name"
    done <<< "$NAMES"
    echo "}"
} > "$OUT"

gofmt -w "$OUT"
echo "Wrote $(grep -c 'true,$' "$OUT") names to ${OUT#"$PROJECT_ROOT"/}"
